package com.esliceu.dwes.domain;

import javax.persistence.*;
import java.util.List;
import java.util.Set;

/**
 * Created by xavi on 25/01/18.
 CREATE TABLE `vers` (
 `idvers` int(11) NOT NULL AUTO_INCREMENT,
 `vers` varchar(1000) NOT NULL,
 `ordre` int(11) NOT NULL,
 `glosa_idglosa` int(11) NOT NULL,
 PRIMARY KEY (`idvers`),
 KEY `fk_vers_glosa_idx` (`glosa_idglosa`),
 CONSTRAINT `fk_vers_glosa` FOREIGN KEY (`glosa_idglosa`) REFERENCES `glosa` (`idglosa`) ON DELETE NO ACTION ON UPDATE NO ACTION
 ) ENGINE=InnoDB AUTO_INCREMENT=549 DEFAULT CHARSET=utf8;

 CREATE TABLE `glosa` (
 `idglosa` int(11) NOT NULL AUTO_INCREMENT,
 `titol` varchar(45) NOT NULL,
 PRIMARY KEY (`idglosa`)
 ) ENGINE=InnoDB AUTO_INCREMENT=122 DEFAULT CHARSET=utf8;
 */

/**
 * Generated by Hibernate:
 * CREATE TABLE `vers` (
 `idvers` int(11) NOT NULL AUTO_INCREMENT,
 `ordre` int(11) DEFAULT NULL,
 `vers` varchar(255) DEFAULT NULL,
 `glosa_idglosa` int(11) DEFAULT NULL,
 PRIMARY KEY (`idvers`),
 KEY `FK7jctssed0j6nd9353vtjr3luv` (`glosa_idglosa`),
 CONSTRAINT `FK7jctssed0j6nd9353vtjr3luv` FOREIGN KEY (`glosa_idglosa`) REFERENCES `glosa` (`idglosa`)
 ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;


 CREATE TABLE `glosa` (
 `idglosa` int(11) NOT NULL AUTO_INCREMENT,
 `titol` varchar(45) NOT NULL,
 PRIMARY KEY (`idglosa`)
 ) ENGINE=InnoDB AUTO_INCREMENT=122 DEFAULT CHARSET=utf8;

 */

@Entity(name = "glosa")
public class Glosa {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "idglosa")
    private Integer id;

    @Column(name = "titol",length = 200, nullable = false)
    private String titol;

    @OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "glosa",
                targetEntity = Vers.class)
    private Set versos = new ChildSet<Vers,Glosa>();

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitol() {
        return titol;
    }

    public void setTitol(String titol) {
        this.titol = titol;
    }

    public Set<Vers> getVersos() {
        if (versos instanceof ChildSet) {
            ((ChildSet)versos).setParent(this);
        }
        return versos;
    }

    public void setVersos(ChildSet versos) {
        this.versos = versos;
    }
}
